include /etc/nginx/active-color.conf;

server {
  listen 80;

  location = /api/health {
    proxy_pass http://active_backend/health;
  }

  location /api/ {
    proxy_pass http://active_backend;
  }

  location / {
    proxy_pass http://active_frontend;
  }
}

server {
  listen 8081;

  location = /api/health {
    proxy_pass http://backend-green:3000/health;
  }

  location /api/ {
    proxy_pass http://backend-green:3000;
  }

  location / {
    proxy_pass http://frontend-green:80;
  }
}
